global:
  imagePullPolicy: IfNotPresent

gateway:
  name: gateway
  host: gateway-service
  image: nginx:alpine
  port: 80

ingress:
  host: chat-bot.local

db:
  name: chat-bot-db
  host: db-service
  image: postgres:18-alpine
  port: 5432
  sslmode: disable
  superuser:
    user: postgres
    password: ""
  admin:
    user: admin
    password: ""
  app:
    user: app
    password: ""
  readonly:
    user: readonly
    password: ""

migrator:
  image: ghcr.io/kuromii5/chat-bot-migrations:v1.0

rabbitmq:
  name: chat-bot-rabbitmq # for Deployment
  host: rabbitmq-service # for Service
  image: rabbitmq:3-management-alpine
  user: admin
  password: ""
  exchange: chat-bot-exchange
  port: 5672
  managementPort: 15672

authService:
  name: auth-service
  host: auth-service
  image: ghcr.io/kuromii5/chat-bot-auth-service:v1.1
  port: 8080
  jwt:
    secret: ""
    accessTokenExpiry: "30m"
    refreshTokenExpiry: "360h"
  logLevel: "info"
  metricsPort: 9000
  serverHost: "0.0.0.0"

chatService:
  name: chat-service
  host: chat-service
  image: ghcr.io/kuromii5/chat-bot-chat-service:v1.1
  port: 8081
  jwt:
    secret: ""
  logLevel: "info"
  metricsPort: 9000
  serverHost: "0.0.0.0"