apiVersion: batch/v1
kind: Job
metadata:
  name: migrator
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: migrator
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      initContainers:
        - name: wait-for-db
          image: {{ .Values.db.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          command: ['sh', '-c', "until pg_isready -h {{ .Values.db.host }} -p {{ .Values.db.port }}; do echo waiting for db; sleep 2; done;"]
      containers:
        - name: migrator-container
          image: {{ .Values.migrator.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: DB_CHAT_BOT_HOST
              value: {{ .Values.db.host }}
            - name: DB_CHAT_BOT_NAME
              value: {{ .Values.db.name }}
            - name: DB_CHAT_BOT_PORT
              value: "{{ .Values.db.port }}"
            - name: DB_CHAT_BOT_SSLMODE
              value: {{ .Values.db.sslmode }}

            - name: ADMIN_USER
              value: {{ .Values.db.admin.user }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-bot-secrets
                  key: db-admin-password

            - name: APP_USER
              value: {{ .Values.db.app.user }}

            - name: READONLY_USER
              value: {{ .Values.db.readonly.user }}

      restartPolicy: OnFailure
