apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-cm
  labels:
    app: db
data:
  init.sh: |-
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOF
      DO \$\$
      BEGIN
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_user WHERE usename = '$ADMIN_USER') THEN
          CREATE USER "$ADMIN_USER" WITH PASSWORD '$ADMIN_PASSWORD';
        END IF;
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_user WHERE usename = '$APP_USER') THEN
          CREATE USER "$APP_USER" WITH PASSWORD '$APP_PASSWORD';
        END IF;
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_user WHERE usename = '$READONLY_USER') THEN
          CREATE USER "$READONLY_USER" WITH PASSWORD '$READONLY_PASSWORD';
        END IF;
      END
      \$\$;

      GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO "$ADMIN_USER", "$APP_USER", "$READONLY_USER";
      GRANT CREATE ON DATABASE "$POSTGRES_DB" TO "$ADMIN_USER";
      GRANT ALL PRIVILEGES ON SCHEMA public TO "$ADMIN_USER";
      
      CREATE SCHEMA IF NOT EXISTS core AUTHORIZATION "$ADMIN_USER";
    EOF

