apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
  annotations:
    "helm.sh/chart-weight": "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db-container
          image: {{ .Values.db.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.db.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.name }}

            - name: POSTGRES_USER
              value: {{ .Values.db.superuser.user }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-bot-secrets
                  key: db-superuser-password

            - name: ADMIN_USER
              value: {{ .Values.db.admin.user }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-bot-secrets
                  key: db-admin-password
              
            - name: APP_USER
              value: {{ .Values.db.app.user }}
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-bot-secrets
                  key: db-app-password

            - name: READONLY_USER
              value: {{ .Values.db.readonly.user }}
            - name: READONLY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-bot-secrets
                  key: db-readonly-password

          # livenessProbe:
          #   exec:
          #     command:
          #       - pg_isready -U {{ .Values.db.user }} -d {{ .Values.db.name }}
          #   failureThreshold: 3
          #   periodSeconds: 1
          #   timeoutSeconds: 2
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/init.sh
              name: db-init-volume
              subPath: init.sh
            - mountPath: /var/lib/postgresql/data
              name: pg-data
      restartPolicy: Always
      volumes:
        - name: db-init-volume
          configMap:
            name: db-init-cm
            items:
              - key: init.sh
                path: init.sh
        - name: pg-data
          persistentVolumeClaim:
            claimName: pg-data
