apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.host }}
spec:
  ports:
    - name: "{{ .Values.db.port }}"
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  selector:
    app: db
