apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.chatService.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:latest
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          command: ['sh', '-c', "until nc -zv {{ .Values.db.host }} {{ .Values.db.port }}; do echo waiting for db; sleep 2; done;"]
      containers:
        - name: chat-container
          image: {{ .Values.chatService.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.chatService.port }}
          envFrom:
            - configMapRef:
                name: "{{ .Values.chatService.name }}-env"
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-bot-secrets
                  key: db-app-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chat-bot-secrets
                  key: jwt-secret
                
      restartPolicy: Always
