apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chatService.host }}
  labels:
    prometheus: scrape
spec:
  ports:
    - name: http
      port: {{ .Values.chatService.port }}
      targetPort: {{ .Values.chatService.port }}
    - name: metrics
      port: {{ .Values.chatService.metricsPort }}
      targetPort: {{ .Values.chatService.metricsPort }}
  selector:
    app: chat