apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.debezium.host }}
spec:
  ports:
    - name: "{{ .Values.debezium.port }}"
      port: {{ .Values.debezium.port }}
      targetPort: {{ .Values.debezium.port }}
  selector:
    app: debezium
