apiVersion: v1
kind: Secret
metadata:
  name: chat-bot-secrets
type: Opaque
data:
  db-superuser-password: {{ .Values.db.superuser.password | b64enc | quote }}
  db-admin-password:     {{ .Values.db.admin.password     | b64enc | quote }}
  db-app-password:       {{ .Values.db.app.password       | b64enc | quote }}
  db-readonly-password:  {{ .Values.db.readonly.password  | b64enc | quote }}
  rabbitmq-password:     {{ .Values.rabbitmq.password | b64enc | quote }}
  rabbitmq-url:          {{ printf "amqp://%s:%s@%s:%v/" .Values.rabbitmq.user .Values.rabbitmq.password .Values.rabbitmq.host .Values.rabbitmq.port | b64enc | quote }}
  jwt-secret:            {{ .Values.authService.jwt.secret | b64enc | quote }}
  smtp-password:         {{ .Values.notificationService.smtp.password | b64enc | quote }}
