apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Release.Name }}-service-monitor"
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      prometheus: scrape
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics