apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.authService.name }}-env"
data:
  DB_HOST: {{ .Values.db.host }}
  DB_NAME: {{ .Values.db.name }}
  DB_PORT: "{{ .Values.db.port }}"
  DB_USER: {{ .Values.db.app.user }}
  DB_SSLMODE: {{ .Values.db.sslmode}}

  LOG_LEVEL: {{ .Values.authService.logLevel }}
  
  JWT_ACCESS_TOKEN_EXPIRY: {{ .Values.authService.jwt.accessTokenExpiry }}
  JWT_REFRESH_TOKEN_EXPIRY: {{ .Values.authService.jwt.refreshTokenExpiry }}

  SERVER_HOST: {{ .Values.authService.serverHost }}
  SERVER_PORT: "{{ .Values.authService.port }}"
  METRICS_PORT: "{{ .Values.authService.metricsPort }}"

  TRACING_ENDPOINT: {{ .Values.authService.tracing.endpoint }}
  TRACING_SAMPLER: "{{ .Values.authService.tracing.sampler }}"