apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.authService.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      initContainers:
        - name: wait-for-db
          image: busybox:latest
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          command: ['sh', '-c', "until nc -zv {{ .Values.db.host }} {{ .Values.db.port }}; do echo waiting for db; sleep 2; done;"]
      containers:
        - name: auth-container
          image: {{ .Values.authService.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.authService.port }}
            - name: metrics
              containerPort: {{ .Values.authService.metricsPort }}
          envFrom:
            - configMapRef:
                name: "{{ .Values.authService.name }}-env"
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-bot-secrets
                  key: db-app-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chat-bot-secrets
                  key: jwt-secret
      restartPolicy: Always
