apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.authService.host }}
spec:
  ports:
    - name: "{{ .Values.authService.port }}"
      port: {{ .Values.authService.port }}
      targetPort: {{ .Values.authService.port }}
  selector:
    app: auth