apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.authService.host }}
  labels:
    prometheus: scrape
spec:
  ports:
    - name: http
      port: {{ .Values.authService.port }}
      targetPort: {{ .Values.authService.port }}
    - name: grpc
      port: {{ .Values.authService.grpcPort }}
      targetPort: {{ .Values.authService.grpcPort }}
    - name: metrics
      port: {{ .Values.authService.metricsPort }}
      targetPort: {{ .Values.authService.metricsPort }}
  selector:
    app: auth